version: "3.9"

services:
  app:
    container_name: descomplica-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - mysql
    ports:
      - 3000:3000

  nginx:
    container_name: descomplica-server
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    links:
      - app

  mysql:
    container_name: descomplica-database
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=descomplica
      - MYSQL_USER=descomplica
      - MYSQL_PASSWORD=descomplica
      - MYSQL_DATABASE=descomplica
    ports:
      - 3306:3306